spring:
  datasource:
    url: jdbc:mysql://111.231.252.16:3306/learn?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: test
    password: 95175300h
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true